### PR TITLE
Problem: sgx provider doesn't work in 0.4 (fixes #386)

### LINKED ISSUE #386: Problem: sgx provider doesn't work in 0.4

### PR DESCRIPTION
**Pull request by tomtau**
Solution: added handling of an extra arg due to the latest enclave runner
plus a fix for the payload reading

### CODE REVIEW

File: providers/sgx/sgx-app/src/main.rs [hunk 1]
```diff
@@ -4,6 +4,10 @@ mod sgx_app;
 #[cfg(target_env = "sgx")]
 fn main() -> std::io::Result<()> {
     let mut args = std::env::args();
+    // enclave-runner had a breaking change that it started to pass the enclave path
+    if args.len() > 2 {
+        let _path = args.next();
```
Comment (leejw51crypto) [inline providers/sgx/sgx-app/src/main.rs:9]: _path is not used ?

File: src/utils.rs [hunk 2]
```diff
@@ -63,10 +63,10 @@ pub fn read_u16_payload<S: Read>(stream: &mut S) -> Result<Vec<u8>, Error> {
         let mut total = 0;
 
         while let Ok(n) = stream.read(&mut state_raw[total..]) {
-            if n == 0 || n + total > l {
+            total += n;
+            if n == 0 || total >= l {
```
Comment (leejw51crypto) [inline src/utils.rs:67]: some comment for this line?

**Review by leejw51crypto — APPROVED** [review]

File: providers/sgx/sgx-app/src/main.rs (hunk 1 above)
Comment (tomtau) [reply providers/sgx/sgx-app/src/main.rs:9]: yes, no need for the enclave path
