### PR TITLE
Problem: unmaintained crate (fixes #414)

### LINKED ISSUE #414: Problem: unmaintained crate
```
Crate:     ansi_term
Version:   0.12.1
Warning:   unmaintained
Title:     ansi_term is Unmaintained
error: 1 denied warning found!
Date:      2021-08-18
ID:        RUSTSEC-2021-0139
URL:       https://rustsec.org/advisories/RUSTSEC-2021-0139
Dependency tree:
ansi_term 0.12.1
├── tracing-subscriber 0.3.15
│   ├── tmkms-softsign 0.4.1
│   ├── tmkms-nitro-helper 0.4.1
│   │   └── tmkms-nitro-enclave 0.4.1
│   ├── tmkms-nitro-enclave 0.4.1
│   ├── tmkms-light-sgx-runner 0.4.1
│   │   └── tmkms-light-sgx-app 0.4.1
│   └── tmkms-light-sgx-app 0.4.1
└── clap 2.34.0
    └── structopt 0.3.26
        ├── tmkms-softsign 0.4.1
        ├── tmkms-nitro-helper 0.4.1
        └── tmkms-light-sgx-runner 0.4.1
```

for `tracing-subscriber`, it may be fixed in the new version: https://github.com/tokio-rs/tracing/pull/2287/commits/a018ede50bb2389ed91192a66bbae6cb1be9614f
for `clap` / `structopt`, it may need a migration: https://github.com/clap-rs/clap/blob/v3-master/CHANGELOG.md#migrating

### PR DESCRIPTION
**Pull request by tomtau**
Solution: switched from structopt to clap v3;
note the ansi_term is still used in tracing-subscriber; it's fixed in the upstream, it just needs a new version of tracing-subscriber to be released

### CODE REVIEW

File: providers/nitro/nitro-helper/src/config.rs [hunk 1]
```diff
@@ -1,8 +1,8 @@
 use crate::shared::AwsCredentials;
+use clap::StructOpt;
```
Comment (devashishdxt) [inline providers/nitro/nitro-helper/src/config.rs:2]: Shouldn't this be `clap::Parser`? Here's the reference documentation for `clap` derive macros: https://docs.rs/clap/latest/clap/_derive/index.html

Comment (tomtau) [reply providers/nitro/nitro-helper/src/config.rs:2]: I followed https://github.com/clap-rs/clap/blob/v3-master/CHANGELOG.md#migrating
> 2. Replace your dependency from `structopt = "..."` to `clap = { version = "3.0", features = ["derive"] }`
> 3. Resolve compiler errors, including
> Update your `use` statements from `structopt` and `structopt::clap` to `clap`

And it seems to build fine?

**Review by devashishdxt — APPROVED** [review]

File: providers/nitro/nitro-helper/Cargo.toml [hunk 2]
```diff
@@ -13,7 +13,7 @@ flex-error = "0.4"
 nix = "0.25"
 serde = { version = "1", features = [ "derive" ] }
 serde_json = "1"
-structopt = "0.3"
+clap = {version = "3", features = ["derive"] }
 subtle-encoding = { version = "0.5", features = [ "bech32-preview" ] }
 sysinfo = "0.26"
```
[the remark this answers is not in the document]
Comment (devashishdxt) [reply providers/nitro/nitro-helper/Cargo.toml:18]: This looks like a false positive. The PR they link was merged in 2021.
